name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2"

      - name: Install dependencies
        run: deno install

      - name: Build project
        run: deno task bundle

      - name: Archive build artifacts
        run: zip -r dist.zip dist/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
